### PR TITLE
Add pixel getter for TrellisM4Express

### PR DESCRIPTION
**Pull request by bbaraban**
Adding the getter function for sub-scripting pixels via location. Very convenient for the project I'm working on.

First time PRing so please let me know anything I can correct.

### CODE REVIEW

**Review by makermelissa — CHANGES_REQUESTED** [review]
Is there a reason you used double underscores for __calculate_pixel_offset? Usually for private function names we start it with a single underscore. Although legal, it makes inheriting classes and overriding those function names a bit more difficult.

**Comment by bbaraban** [comment]
> Is there a reason you used double underscores for __calculate_pixel_offset? Usually for private function names we start it with a single underscore. Although legal, it makes inheriting classes and overriding those function names a bit more difficult.

It was my best guess at what was right =). I'm not 100% on the design patterns used in these libraries as I'm new but it seemed like it was internal implementation that shouldn't be overridden or exposed. Also  _NeoPixelArray was written specifically for TrellisM4Express so I think it would be unlikely anyone would extend off _NeoPixelArray in the TrellisM4 library.

I'm also 100% open to changing it to _, just let me know if you would prefer that.

Thank you

**Comment by makermelissa** [comment]
Thanks. Yeah, let's change it to a single underscore. You're probably correct that it's unlikely to be extended, but I'd like to leave that option open.

**Review by makermelissa — APPROVED** [review]

**Comment by makermelissa** [comment]
Looks good. I just tested the examples on my Trellis M4 and they all worked fine.

**Comment by makermelissa** [comment]
Thank you!

**Pull request merged**
